// llmNode.js
// -----------------------------------------------------------------------------
// LLMNode represents an AI processing unit in the pipeline.
// It is built on top of the shared BaseNode abstraction and focuses ONLY on
// LLM-specific configuration such as prompts and model selection.
//
// Key ideas demonstrated here:
// - Reuse of BaseNode for layout, actions, and styling
// - Separation of node-specific logic from shared UI
// - Handles always remain visible (even when minimized)
// - Controlled inputs for predictable state updates
// -----------------------------------------------------------------------------

import { useState } from "react";
import { Handle, Position } from "reactflow";
import { BaseNode } from "./BaseNode";
import llmIcon from "../assets/llm-icon.png";

export const LLMNode = ({ id, data }) => {
  // ---------------------------------------------------------------------------
  // Local state for LLM configuration
  // These values belong to THIS node only, so they are kept as local component
  // state instead of global Zustand state.
  // ---------------------------------------------------------------------------

  const [systemPrompt, setSystemPrompt] = useState(
    data?.systemPrompt ||
      "Answer the Question based on Context in a professional manner."
  );

  const [userPrompt, setUserPrompt] = useState(data?.userPrompt || "");

  const [model, setModel] = useState(data?.model || "gpt-4");

  // ---------------------------------------------------------------------------
  // React Flow Handles
  // - Target handle (left): input/context into the LLM
  // - Source handle (right): output generated by the LLM
  // Handles are intentionally small and always rendered so graph connectivity
  // is preserved even when the node is minimized.
  // ---------------------------------------------------------------------------

  const handles = (
    <>
      <Handle
        type="target"
        position={Position.Left}
        id={`${id}-input`}
        style={{
          width: 8,
          height: 8,
          background: "#fff",
          border: "2px solid #6366f1",
          borderRadius: "50%",
          left: -4,
        }}
      />

      <Handle
        type="source"
        position={Position.Right}
        id={`${id}-output`}
        style={{
          width: 8,
          height: 8,
          background: "#fff",
          border: "2px solid #6366f1",
          borderRadius: "50%",
          right: -4,
        }}
      />
    </>
  );

  return (
    // -------------------------------------------------------------------------
    // BaseNode usage
    // - BaseNode handles layout, header, delete/minimize actions
    // - LLMNode injects ONLY its unique UI and logic via children
    // -------------------------------------------------------------------------
    <BaseNode id={id} title="LLM" icon={llmIcon} handles={handles}>
      {/* ---------------------------------------------------------------------
          Node Identifier
          - Displays a readable node name derived from the node id
          - Helps users identify the node in large pipelines
         --------------------------------------------------------------------- */}
      <div
        style={{
          padding: "8px 10px",
          background: "#f8fafc",
          borderRadius: 4,
          marginBottom: 10,
          textAlign: "center",
          fontSize: 13,
          color: "#1e293b",
        }}
      >
        {id.replace("llm-", "llm_")}
      </div>

      {/* ---------------------------------------------------------------------
          System Prompt Section
          - Represents system-level instructions for the LLM
          - Controlled textarea ensures predictable updates
         --------------------------------------------------------------------- */}
      <div style={{ marginBottom: 10 }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 4,
          }}
        >
          <span style={{ fontSize: 12, color: "#64748b" }}>
            System (Instructions) ⓘ
          </span>
          <span style={{ fontSize: 11, color: "#6366f1" }}>Text</span>
        </div>

        <textarea
          style={{
            width: "100%",
            padding: "8px 10px",
            borderRadius: 4,
            border: "1px solid #e2e8f0",
            fontSize: 12,
            color: "#1e293b",
            background: "#fff",
            outline: "none",
            resize: "vertical",
            minHeight: 60,
            boxSizing: "border-box",
            fontFamily: "inherit",
          }}
          value={systemPrompt}
          onChange={(e) => setSystemPrompt(e.target.value)}
        />
      </div>

      {/* ---------------------------------------------------------------------
          User Prompt Section
          - Main prompt that can include dynamic variables
          - Placeholder hints users about {{variable}} support
         --------------------------------------------------------------------- */}
      <div style={{ marginBottom: 10 }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 4,
          }}
        >
          <span style={{ fontSize: 12, color: "#64748b" }}>Prompt ⓘ</span>
          <span style={{ fontSize: 11, color: "#6366f1" }}>Text</span>
        </div>

        <textarea
          style={{
            width: "100%",
            padding: "8px 10px",
            borderRadius: 4,
            border: "1px solid #e2e8f0",
            fontSize: 12,
            color: "#1e293b",
            background: "#fff",
            outline: "none",
            resize: "vertical",
            minHeight: 60,
            boxSizing: "border-box",
            fontFamily: "inherit",
          }}
          value={userPrompt}
          onChange={(e) => setUserPrompt(e.target.value)}
          placeholder='Type "{{" to use variables'
        />
      </div>

      {/* ---------------------------------------------------------------------
          Model Selection
          - Allows switching between different LLM models
          - Controlled select keeps state predictable
         --------------------------------------------------------------------- */}
      <div>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 4,
          }}
        >
          <span style={{ fontSize: 12, color: "#64748b" }}>Model ⓘ</span>
          <span style={{ fontSize: 11, color: "#6366f1" }}>Dropdown</span>
        </div>

        <select
          style={{
            width: "100%",
            padding: "8px 10px",
            borderRadius: 4,
            border: "1px solid #e2e8f0",
            fontSize: 13,
            color: "#1e293b",
            background: "#fff",
            outline: "none",
            cursor: "pointer",
            boxSizing: "border-box",
          }}
          value={model}
          onChange={(e) => setModel(e.target.value)}
        >
          <option value="gpt-4">gpt-4</option>
          <option value="gpt-3.5-turbo">gpt-3.5-turbo</option>
          <option value="gpt-4-turbo">gpt-4-turbo</option>
        </select>
      </div>
    </BaseNode>
  );
};
